version: '3'
services:
  nginx:
    image: nginx:1.15.3-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php-fpm
    restart: always
  php-fpm:
    build: "./docker/php-fpm/"
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zphp.ini
    restart: always
  composer:
    image: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
